#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLThuVien")]
	public partial class QLThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietPhieuMuon(ChiTietPhieuMuon instance);
    partial void UpdateChiTietPhieuMuon(ChiTietPhieuMuon instance);
    partial void DeleteChiTietPhieuMuon(ChiTietPhieuMuon instance);
    partial void InsertDocGia(DocGia instance);
    partial void UpdateDocGia(DocGia instance);
    partial void DeleteDocGia(DocGia instance);
    partial void InsertLoaiSach(LoaiSach instance);
    partial void UpdateLoaiSach(LoaiSach instance);
    partial void DeleteLoaiSach(LoaiSach instance);
    partial void InsertNganhKhoa(NganhKhoa instance);
    partial void UpdateNganhKhoa(NganhKhoa instance);
    partial void DeleteNganhKhoa(NganhKhoa instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhaXuatBan(NhaXuatBan instance);
    partial void UpdateNhaXuatBan(NhaXuatBan instance);
    partial void DeleteNhaXuatBan(NhaXuatBan instance);
    partial void InsertPhieuMuonSach(PhieuMuonSach instance);
    partial void UpdatePhieuMuonSach(PhieuMuonSach instance);
    partial void DeletePhieuMuonSach(PhieuMuonSach instance);
    partial void InsertSach(Sach instance);
    partial void UpdateSach(Sach instance);
    partial void DeleteSach(Sach instance);
    partial void InsertViPham(ViPham instance);
    partial void UpdateViPham(ViPham instance);
    partial void DeleteViPham(ViPham instance);
    #endregion
		
		public QLThuVienDataContext() : 
				base(global::DTO.Properties.Settings.Default.QLThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietPhieuMuon> ChiTietPhieuMuons
		{
			get
			{
				return this.GetTable<ChiTietPhieuMuon>();
			}
		}
		
		public System.Data.Linq.Table<DocGia> DocGias
		{
			get
			{
				return this.GetTable<DocGia>();
			}
		}
		
		public System.Data.Linq.Table<LoaiSach> LoaiSaches
		{
			get
			{
				return this.GetTable<LoaiSach>();
			}
		}
		
		public System.Data.Linq.Table<NganhKhoa> NganhKhoas
		{
			get
			{
				return this.GetTable<NganhKhoa>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhaXuatBan> NhaXuatBans
		{
			get
			{
				return this.GetTable<NhaXuatBan>();
			}
		}
		
		public System.Data.Linq.Table<PhieuMuonSach> PhieuMuonSaches
		{
			get
			{
				return this.GetTable<PhieuMuonSach>();
			}
		}
		
		public System.Data.Linq.Table<Sach> Saches
		{
			get
			{
				return this.GetTable<Sach>();
			}
		}
		
		public System.Data.Linq.Table<ViPham> ViPhams
		{
			get
			{
				return this.GetTable<ViPham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuMuon")]
	public partial class ChiTietPhieuMuon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieuMuon;
		
		private int _MaSach;
		
		private EntityRef<PhieuMuonSach> _PhieuMuonSach;
		
		private EntityRef<Sach> _Sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuMuonChanging(int value);
    partial void OnMaPhieuMuonChanged();
    partial void OnMaSachChanging(int value);
    partial void OnMaSachChanged();
    #endregion
		
		public ChiTietPhieuMuon()
		{
			this._PhieuMuonSach = default(EntityRef<PhieuMuonSach>);
			this._Sach = default(EntityRef<Sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuMuon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhieuMuon
		{
			get
			{
				return this._MaPhieuMuon;
			}
			set
			{
				if ((this._MaPhieuMuon != value))
				{
					if (this._PhieuMuonSach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuMuonChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuMuon = value;
					this.SendPropertyChanged("MaPhieuMuon");
					this.OnMaPhieuMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._Sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuMuonSach_ChiTietPhieuMuon", Storage="_PhieuMuonSach", ThisKey="MaPhieuMuon", OtherKey="id", IsForeignKey=true)]
		public PhieuMuonSach PhieuMuonSach
		{
			get
			{
				return this._PhieuMuonSach.Entity;
			}
			set
			{
				PhieuMuonSach previousValue = this._PhieuMuonSach.Entity;
				if (((previousValue != value) 
							|| (this._PhieuMuonSach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuMuonSach.Entity = null;
						previousValue.ChiTietPhieuMuons.Remove(this);
					}
					this._PhieuMuonSach.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuMuons.Add(this);
						this._MaPhieuMuon = value.id;
					}
					else
					{
						this._MaPhieuMuon = default(int);
					}
					this.SendPropertyChanged("PhieuMuonSach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_ChiTietPhieuMuon", Storage="_Sach", ThisKey="MaSach", OtherKey="id", IsForeignKey=true)]
		public Sach Sach
		{
			get
			{
				return this._Sach.Entity;
			}
			set
			{
				Sach previousValue = this._Sach.Entity;
				if (((previousValue != value) 
							|| (this._Sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sach.Entity = null;
						previousValue.ChiTietPhieuMuons.Remove(this);
					}
					this._Sach.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuMuons.Add(this);
						this._MaSach = value.id;
					}
					else
					{
						this._MaSach = default(int);
					}
					this.SendPropertyChanged("Sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocGia")]
	public partial class DocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mssv;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.DateTime _NgayMoThe;
		
		private bool _Disable;
		
		private EntitySet<PhieuMuonSach> _PhieuMuonSaches;
		
		private EntitySet<ViPham> _ViPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmssvChanging(string value);
    partial void OnmssvChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgayMoTheChanging(System.DateTime value);
    partial void OnNgayMoTheChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public DocGia()
		{
			this._PhieuMuonSaches = new EntitySet<PhieuMuonSach>(new Action<PhieuMuonSach>(this.attach_PhieuMuonSaches), new Action<PhieuMuonSach>(this.detach_PhieuMuonSaches));
			this._ViPhams = new EntitySet<ViPham>(new Action<ViPham>(this.attach_ViPhams), new Action<ViPham>(this.detach_ViPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="NChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMoThe", DbType="Date NOT NULL")]
		public System.DateTime NgayMoThe
		{
			get
			{
				return this._NgayMoThe;
			}
			set
			{
				if ((this._NgayMoThe != value))
				{
					this.OnNgayMoTheChanging(value);
					this.SendPropertyChanging();
					this._NgayMoThe = value;
					this.SendPropertyChanged("NgayMoThe");
					this.OnNgayMoTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_PhieuMuonSach", Storage="_PhieuMuonSaches", ThisKey="mssv", OtherKey="NguoiMuon")]
		public EntitySet<PhieuMuonSach> PhieuMuonSaches
		{
			get
			{
				return this._PhieuMuonSaches;
			}
			set
			{
				this._PhieuMuonSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_ViPham", Storage="_ViPhams", ThisKey="mssv", OtherKey="mssv")]
		public EntitySet<ViPham> ViPhams
		{
			get
			{
				return this._ViPhams;
			}
			set
			{
				this._ViPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuMuonSaches(PhieuMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = this;
		}
		
		private void detach_PhieuMuonSaches(PhieuMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = null;
		}
		
		private void attach_ViPhams(ViPham entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = this;
		}
		
		private void detach_ViPhams(ViPham entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSach")]
	public partial class LoaiSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pid;
		
		private string _Ten;
		
		private bool _Disable;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public LoaiSach()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.Always, DbType="VarChar(8)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSach_Sach", Storage="_Saches", ThisKey="id", OtherKey="LoaiSach")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSach1 = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSach1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NganhKhoa")]
	public partial class NganhKhoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pid;
		
		private string _Ten;
		
		private bool _Disable;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public NganhKhoa()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.Always, DbType="VarChar(9)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhKhoa_Sach", Storage="_Saches", ThisKey="id", OtherKey="NganhKhoa")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NganhKhoa1 = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NganhKhoa1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pid;
		
		private string _Ten;
		
		private System.DateTime _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _ChucVu;
		
		private string _MatKhau;
		
		private bool _Disable;
		
		private EntitySet<PhieuMuonSach> _PhieuMuonSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public NhanVien()
		{
			this._PhieuMuonSaches = new EntitySet<PhieuMuonSach>(new Action<PhieuMuonSach>(this.attach_PhieuMuonSaches), new Action<PhieuMuonSach>(this.detach_PhieuMuonSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.Always, DbType="VarChar(8)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NChar(10)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuMuonSach", Storage="_PhieuMuonSaches", ThisKey="id", OtherKey="NguoiLapPhieu")]
		public EntitySet<PhieuMuonSach> PhieuMuonSaches
		{
			get
			{
				return this._PhieuMuonSaches;
			}
			set
			{
				this._PhieuMuonSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuMuonSaches(PhieuMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuMuonSaches(PhieuMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaXuatBan")]
	public partial class NhaXuatBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pid;
		
		private string _Ten;
		
		private bool _Disable;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public NhaXuatBan()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.Always, DbType="VarChar(9)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaXuatBan_Sach", Storage="_Saches", ThisKey="id", OtherKey="NhaXB")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NhaXuatBan = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NhaXuatBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuMuonSach")]
	public partial class PhieuMuonSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pid;
		
		private System.DateTime _NgayMuon;
		
		private System.DateTime _HanTra;
		
		private System.Nullable<int> _NguoiLapPhieu;
		
		private string _NguoiMuon;
		
		private bool _Disable;
		
		private EntitySet<ChiTietPhieuMuon> _ChiTietPhieuMuons;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<DocGia> _DocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OnNgayMuonChanging(System.DateTime value);
    partial void OnNgayMuonChanged();
    partial void OnHanTraChanging(System.DateTime value);
    partial void OnHanTraChanged();
    partial void OnNguoiLapPhieuChanging(System.Nullable<int> value);
    partial void OnNguoiLapPhieuChanged();
    partial void OnNguoiMuonChanging(string value);
    partial void OnNguoiMuonChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public PhieuMuonSach()
		{
			this._ChiTietPhieuMuons = new EntitySet<ChiTietPhieuMuon>(new Action<ChiTietPhieuMuon>(this.attach_ChiTietPhieuMuons), new Action<ChiTietPhieuMuon>(this.detach_ChiTietPhieuMuons));
			this._NhanVien = default(EntityRef<NhanVien>);
			this._DocGia = default(EntityRef<DocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.Always, DbType="VarChar(9)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="Date NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanTra", DbType="Date NOT NULL")]
		public System.DateTime HanTra
		{
			get
			{
				return this._HanTra;
			}
			set
			{
				if ((this._HanTra != value))
				{
					this.OnHanTraChanging(value);
					this.SendPropertyChanging();
					this._HanTra = value;
					this.SendPropertyChanged("HanTra");
					this.OnHanTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLapPhieu", DbType="Int")]
		public System.Nullable<int> NguoiLapPhieu
		{
			get
			{
				return this._NguoiLapPhieu;
			}
			set
			{
				if ((this._NguoiLapPhieu != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NguoiLapPhieu = value;
					this.SendPropertyChanged("NguoiLapPhieu");
					this.OnNguoiLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiMuon", DbType="NChar(11)")]
		public string NguoiMuon
		{
			get
			{
				return this._NguoiMuon;
			}
			set
			{
				if ((this._NguoiMuon != value))
				{
					if (this._DocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiMuonChanging(value);
					this.SendPropertyChanging();
					this._NguoiMuon = value;
					this.SendPropertyChanged("NguoiMuon");
					this.OnNguoiMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuMuonSach_ChiTietPhieuMuon", Storage="_ChiTietPhieuMuons", ThisKey="id", OtherKey="MaPhieuMuon")]
		public EntitySet<ChiTietPhieuMuon> ChiTietPhieuMuons
		{
			get
			{
				return this._ChiTietPhieuMuons;
			}
			set
			{
				this._ChiTietPhieuMuons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuMuonSach", Storage="_NhanVien", ThisKey="NguoiLapPhieu", OtherKey="id", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuMuonSaches.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuMuonSaches.Add(this);
						this._NguoiLapPhieu = value.id;
					}
					else
					{
						this._NguoiLapPhieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_PhieuMuonSach", Storage="_DocGia", ThisKey="NguoiMuon", OtherKey="mssv", IsForeignKey=true)]
		public DocGia DocGia
		{
			get
			{
				return this._DocGia.Entity;
			}
			set
			{
				DocGia previousValue = this._DocGia.Entity;
				if (((previousValue != value) 
							|| (this._DocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DocGia.Entity = null;
						previousValue.PhieuMuonSaches.Remove(this);
					}
					this._DocGia.Entity = value;
					if ((value != null))
					{
						value.PhieuMuonSaches.Add(this);
						this._NguoiMuon = value.mssv;
					}
					else
					{
						this._NguoiMuon = default(string);
					}
					this.SendPropertyChanged("DocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuMuons(ChiTietPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuMuonSach = this;
		}
		
		private void detach_ChiTietPhieuMuons(ChiTietPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuMuonSach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sach")]
	public partial class Sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pid;
		
		private string _Ten;
		
		private string _TacGia;
		
		private System.Nullable<int> _NamXB;
		
		private System.Nullable<int> _NhaXB;
		
		private string _MoTa;
		
		private string _DuongDanAnh;
		
		private System.Nullable<int> _LoaiSach;
		
		private System.Nullable<int> _NganhKhoa;
		
		private int _SoLuongHienCo;
		
		private int _SoLuongDaMuon;
		
		private bool _Disable;

        private ChiTietPhieuMuon _phieuMuonRef;

        public ChiTietPhieuMuon PhieuMuonRef
        {
            get
            {
                return _phieuMuonRef;
            } set
            {
                _phieuMuonRef = value;
            }
        }
		
		private EntitySet<ChiTietPhieuMuon> _ChiTietPhieuMuons;
		
		private EntityRef<LoaiSach> _LoaiSach1;
		
		private EntityRef<NganhKhoa> _NganhKhoa1;
		
		private EntityRef<NhaXuatBan> _NhaXuatBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnTacGiaChanging(string value);
    partial void OnTacGiaChanged();
    partial void OnNamXBChanging(System.Nullable<int> value);
    partial void OnNamXBChanged();
    partial void OnNhaXBChanging(System.Nullable<int> value);
    partial void OnNhaXBChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnDuongDanAnhChanging(string value);
    partial void OnDuongDanAnhChanged();
    partial void OnLoaiSachChanging(System.Nullable<int> value);
    partial void OnLoaiSachChanged();
    partial void OnNganhKhoaChanging(System.Nullable<int> value);
    partial void OnNganhKhoaChanged();
    partial void OnSoLuongHienCoChanging(int value);
    partial void OnSoLuongHienCoChanged();
    partial void OnSoLuongDaMuonChanging(int value);
    partial void OnSoLuongDaMuonChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public Sach()
		{
			this._ChiTietPhieuMuons = new EntitySet<ChiTietPhieuMuon>(new Action<ChiTietPhieuMuon>(this.attach_ChiTietPhieuMuons), new Action<ChiTietPhieuMuon>(this.detach_ChiTietPhieuMuons));
			this._LoaiSach1 = default(EntityRef<LoaiSach>);
			this._NganhKhoa1 = default(EntityRef<NganhKhoa>);
			this._NhaXuatBan = default(EntityRef<NhaXuatBan>);
			OnCreated();
		}

        public Sach(ChiTietPhieuMuon phieuMuonRef) : this()
        {
            _phieuMuonRef = phieuMuonRef;
        }
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging("id", _id, value);
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.Always, DbType="VarChar(10)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
                    if (this.SendPropertyChanging("pid", _pid, value))
                    {
                        this._pid = value;
                        this.SendPropertyChanged("pid");
                        this.OnpidChanged();
                    }
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging("Ten", _Ten, value);
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(70)")]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this.OnTacGiaChanging(value);
					this.SendPropertyChanging("TacGia", _TacGia, value);
					this._TacGia = value;
					this.SendPropertyChanged("TacGia");
					this.OnTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="Int")]
		public System.Nullable<int> NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this.OnNamXBChanging(value);
					this.SendPropertyChanging("NamXB", _NamXB, value);
					this._NamXB = value;
					this.SendPropertyChanged("NamXB");
					this.OnNamXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="Int")]
		public System.Nullable<int> NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					if (this._NhaXuatBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhaXBChanging(value);
					this.SendPropertyChanging("NhaXB", _NhaXB, value);
					this._NhaXB = value;
					this.SendPropertyChanged("NhaXB");
					this.OnNhaXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(100)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging("MoTa", _MoTa, value);
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongDanAnh", DbType="NVarChar(200)")]
		public string DuongDanAnh
		{
			get
			{
				return this._DuongDanAnh;
			}
			set
			{
				if ((this._DuongDanAnh != value))
				{
					this.OnDuongDanAnhChanging(value);
					this.SendPropertyChanging("DuongDanAnh", _DuongDanAnh, value);
					this._DuongDanAnh = value;
					this.SendPropertyChanged("DuongDanAnh");
					this.OnDuongDanAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiSach", DbType="Int")]
		public System.Nullable<int> LoaiSach
		{
			get
			{
				return this._LoaiSach;
			}
			set
			{
				if ((this._LoaiSach != value))
				{
					if (this._LoaiSach1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiSachChanging(value);
					this.SendPropertyChanging("LoaiSach", _LoaiSach, value);
					this._LoaiSach = value;
					this.SendPropertyChanged("LoaiSach");
					this.OnLoaiSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhKhoa", DbType="Int")]
		public System.Nullable<int> NganhKhoa
		{
			get
			{
				return this._NganhKhoa;
			}
			set
			{
				if ((this._NganhKhoa != value))
				{
					if (this._NganhKhoa1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNganhKhoaChanging(value);
					this.SendPropertyChanging("NganhKhoa", _NganhKhoa, value);
					this._NganhKhoa = value;
					this.SendPropertyChanged("NganhKhoa");
					this.OnNganhKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongHienCo", DbType="Int NOT NULL")]
		public int SoLuongHienCo
		{
			get
			{
				return this._SoLuongHienCo;
			}
			set
			{
				if ((this._SoLuongHienCo != value))
				{
					this.OnSoLuongHienCoChanging(value);
					this.SendPropertyChanging("SoLuongHienCo", _SoLuongHienCo, value);
					this._SoLuongHienCo = value;
					this.SendPropertyChanged("SoLuongHienCo");
					this.OnSoLuongHienCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDaMuon", DbType="Int NOT NULL")]
		public int SoLuongDaMuon
		{
			get
			{
				return this._SoLuongDaMuon;
			}
			set
			{
				if ((this._SoLuongDaMuon != value))
				{
					this.OnSoLuongDaMuonChanging(value);
					this.SendPropertyChanging("SoLuongDaMuon", _SoLuongDaMuon, value);
                    this._SoLuongDaMuon = value;
					this.SendPropertyChanged("SoLuongDaMuon");
					this.OnSoLuongDaMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging("Disable", _Disable, value);
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_ChiTietPhieuMuon", Storage="_ChiTietPhieuMuons", ThisKey="id", OtherKey="MaSach")]
		public EntitySet<ChiTietPhieuMuon> ChiTietPhieuMuons
		{
			get
			{
				return this._ChiTietPhieuMuons;
			}
			set
			{
				this._ChiTietPhieuMuons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSach_Sach", Storage="_LoaiSach1", ThisKey="LoaiSach", OtherKey="id", IsForeignKey=true)]
		public LoaiSach LoaiSach1
		{
			get
			{
				return this._LoaiSach1.Entity;
			}
			set
			{
				LoaiSach previousValue = this._LoaiSach1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiSach1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging("LoaiSach1", _LoaiSach1.Entity, value);
                    if ((previousValue != null))
					{
						this._LoaiSach1.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._LoaiSach1.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._LoaiSach = value.id;
					}
					else
					{
						this._LoaiSach = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiSach1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhKhoa_Sach", Storage="_NganhKhoa1", ThisKey="NganhKhoa", OtherKey="id", IsForeignKey=true)]
		public NganhKhoa NganhKhoa1
		{
			get
			{
				return this._NganhKhoa1.Entity;
			}
			set
			{
				NganhKhoa previousValue = this._NganhKhoa1.Entity;
				if (((previousValue != value) 
							|| (this._NganhKhoa1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging("NganhKhoa1", _NganhKhoa1.Entity, value);
                    if ((previousValue != null))
					{
						this._NganhKhoa1.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._NganhKhoa1.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._NganhKhoa = value.id;
					}
					else
					{
						this._NganhKhoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("NganhKhoa1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaXuatBan_Sach", Storage="_NhaXuatBan", ThisKey="NhaXB", OtherKey="id", IsForeignKey=true)]
		public NhaXuatBan NhaXuatBan
		{
			get
			{
				return this._NhaXuatBan.Entity;
			}
			set
			{
				NhaXuatBan previousValue = this._NhaXuatBan.Entity;
				if (((previousValue != value) 
							|| (this._NhaXuatBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging("NhaXuatBan", _NhaXuatBan.Entity, value);
					if ((previousValue != null))
					{
						this._NhaXuatBan.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._NhaXuatBan.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._NhaXB = value.id;
					}
					else
					{
						this._NhaXB = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaXuatBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;

        protected virtual bool SendPropertyChanging<T>(string propertyName, T previousValue, T currentValue)
		{
			if ((this.PropertyChanging != null))
			{
                var args = new PropertyChangingCancelEventArgs<T>(propertyName, previousValue, currentValue);
                this.PropertyChanging(this, args);
                return !args.Cancel;
			}
            return true;
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuMuons(ChiTietPhieuMuon entity)
		{
			//this.SendPropertyChanging("ChiTietPhieuMuon", entity, _ChiTietPhieuMuons);
			entity.Sach = this;
		}
		
		private void detach_ChiTietPhieuMuons(ChiTietPhieuMuon entity)
		{
			//this.SendPropertyChanging();
			entity.Sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViPham")]
	public partial class ViPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _NoiDung;
		
		private string _mssv;
		
		private bool _Disable;
		
		private EntityRef<DocGia> _DocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnmssvChanging(string value);
    partial void OnmssvChanged();
    partial void OnDisableChanging(bool value);
    partial void OnDisableChanged();
    #endregion
		
		public ViPham()
		{
			this._DocGia = default(EntityRef<DocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					if (this._DocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disable", DbType="Bit NOT NULL")]
		public bool Disable
		{
			get
			{
				return this._Disable;
			}
			set
			{
				if ((this._Disable != value))
				{
					this.OnDisableChanging(value);
					this.SendPropertyChanging();
					this._Disable = value;
					this.SendPropertyChanged("Disable");
					this.OnDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_ViPham", Storage="_DocGia", ThisKey="mssv", OtherKey="mssv", IsForeignKey=true)]
		public DocGia DocGia
		{
			get
			{
				return this._DocGia.Entity;
			}
			set
			{
				DocGia previousValue = this._DocGia.Entity;
				if (((previousValue != value) 
							|| (this._DocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DocGia.Entity = null;
						previousValue.ViPhams.Remove(this);
					}
					this._DocGia.Entity = value;
					if ((value != null))
					{
						value.ViPhams.Add(this);
						this._mssv = value.mssv;
					}
					else
					{
						this._mssv = default(string);
					}
					this.SendPropertyChanged("DocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
